### ISSUE TITLE
Morning Session

### ISSUE THREAD

**Issue by orozCoding** [clintonjosephs/LeaderBoard#5]
Great work with your project! Your code looks clean, it's very readable and it's working perfectly! 
<img src="https://media4.giphy.com/media/kdQuvu0LtCEjxYgTcS/giphy.gif"/>

_Here are some suggestions that could make your code even better!:_
- In your comments, there are some typos that could be easily fixed.
- Since you're already adding such amazing extra features, we think it would be great to make the leaderboard automatically refresh once a score it's been added.
- Consider hiding the vertical scrollbar from the leaderboard when its size is not really big enough to expand the viewport.
- Whenever a user tries to refresh the leaderboard when this is empty, it would be great to display a message different from the default one (since it's not really retrieving any content). 

**Congratulations on your project! Keep it going. ❤️**

**Comment by clintonjosephs** [comment]
Thank you for raising these issues, my project sure looks and performs better now. All issues mentioned have been implemented.
