### ISSUE TITLE
Mention MIT license rather All Rights Reserved

### ISSUE THREAD

**Issue by ahangarha** [clintonjosephs/LeaderBoard#6]
I just noticed you added a copyright notice below the page and mentioned "All Rights Reserved". Since the project is under MIT license and is a Free/Libre and Open Source software, I suggest to mention this. Of course your are the copyright holder but your are giving certain freedom to the user as per MIT license.

It is also more cool :wink:

**Comment by clintonjosephs** [comment]
Thank you very much for this, I will make the necessary changes
