### ISSUE TITLE
Improve loading indicator to follow the overall design

### ISSUE THREAD

**Issue by ahangarha** [clintonjosephs/LeaderBoard#7]
The project is implemented very neatly. All components follow the same design except the loading indicator.

![image](https://user-images.githubusercontent.com/11241315/151352965-74b12c8d-10ba-42bb-8226-fa6132835bd1.png)

Would be nice if you can design this also in such way it follow the overall design of the project.

**Comment by clintonjosephs** [comment]
Thank you for opening this issue, i have changed the loading indicator.
