### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by Sboursen** [clintonjosephs/LeaderBoard#8]
### Hi @clintonjosephs,

I visited your page and generally speaking, your work looks good in every aspect :clap:
However, I believe it will be :cool: to additionally implement **client-side form validation** to your project. I will keep your data consistent, and also serve as an additional barrier against malicious users.
Please use this [Link](https://github.com/microverseinc/curriculum-html-css/blob/main/client_side_validation.md), it's a reminder on how to implement the aforementioned feature.

Happy coding :rocket:

**Comment by clintonjosephs** [comment]
Thank you so much for raising this issue, my project performs better now with the validations.
